steps:
  - id: "Run Poetry Installation and Setup"
    name: python:3.12-slim
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install poetry && poetry install --no-root
options:
  logging: CLOUD_LOGGING_ONLY
