steps:
  - id: "Run Poetry Installation and Setup"
    name: python:3.12-slim
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install poetry && poetry install --no-root

  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "europe-west1-docker.pkg.dev/HE22-Blog-Serkan/rankingsladder-repo/rankingsladder:latest"
      - "."

  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "europe-west1-docker.pkg.dev/HE22-Blog-Serkan/rankingsladder-repo/rankingsladder:latest"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "europe-west1-docker.pkg.dev/HE22-Blog-Serkan/rankingsladder-repo/rankingsladder:latest"
