steps:
  - id: "Install Dependencies"
    name: python:3.12-slim
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install poetry && poetry install

  - id: "Build Docker Image"
    name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - "."

  - id: "Push Docker Image"
    name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"

  - id: "Deploy to Cloud Run"
    name: gcr.io/cloud-builders/gcloud
    args:
      - "run"
      - "deploy"
      - "$REPO_NAME"
      - "--image"
      - "gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA"
      - "--region"
      - "europe-west1"  # Region auf europa-west1 geändert
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

options:
  logging: CLOUD_LOGGING_ONLY
