steps:
  - id: "Run Tests"
    name: python:3.12-slim
    entrypoint: bash
    args:
      - "-c"
      - |
        pip install poetry && poetry install && poetry run pytest

  - id: "Build Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/he22-blog-serkan/rankingsladder:$COMMIT_SHA"
      - "."

  - id: "Push Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/he22-blog-serkan/rankingsladder:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
